name: Streamlit 24-7 Keep Awake Daemon
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit Deployment Engine
        run: |
          curl -I -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" https://imou-call-raavigunta.streamlit.app/
